### ISSUE TITLE
Plans to publish?

### ISSUE THREAD

**Issue by Spirarel** [haberdashPI/vscode-modal-keys#1]
Hi there, do you have any plans to publish to the vsc marketplace or is this more of a private project?

**Comment by haberdashPI** [comment]
I do! I am trying to work out a few more bugs and finish revising the documentation before I publish. Feel free to make use of it (Im happy to explain how to install before it's published).

**Comment by Spirarel** [comment]
Great! Well, I will definitely be playing with this in the meantime. Thank you for the offer for help! I just made a vsix with vsce; I assume that's the typical route?

Are there plans for a Kakoune present in addition to vim? I actually just learned of Kakoune from a post you made mentioning it on Julia's discourse.

**Comment by haberdashPI** [comment]
Awesome! To answer your questions:

1. Yes, vsix with vsce is what I do.
2. For an initial release, no. I use my own custom, kakaune-*like* keymap, I will definitely include that in the presets. A kakune-preset is an obvious addition, though. Would certainly appreciate a PR in that direction.

**Comment by haberdashPI** [comment]
This is now published on the marketplace.
