### ISSUE TITLE
Unable to import vim preset keybindings

### ISSUE THREAD

**Issue by Spirarel** [haberdashPI/vscode-modal-keys#2]
**Env**
macOS 10.14.6
vsc 1.56.2
ModalKeys "2.1"

**Observation**
I'm unable to import the vim.js preset after installing ModalKeys from a vsix file.
The log states
```
Validating keybindings in 'settings.json'...
ERROR: Missing valid normal mode keybindings. Keybindings not updated.
Validation completed successfully.
```

**Steps to reproduce**
Install ModalKeys, have no settings for modalkeys configured in your settings.json, try to import vim.js

**Comment by haberdashPI** [comment]
That makes sense, I'm still in the process of porting them from the old format used in ModalEdit. I haven't actually tested the vim bindings at all yet; I've been dogfood-ing this extension by using it with my own setup which is not vim-like but kakoune-like.

**Comment by Spirarel** [comment]
Oh gotcha. Sorry, I don't really know the lines between ModalEdit's base and ModalKey's additions.

**Comment by haberdashPI** [comment]
Should be importable now. I have not used the VIM presets extensively yet, myself. So if you do end up using this extension, I would appreciate a report of any issues you find. They are meant more as a springboard for setting up your own config file, but they should still work reasonably well on their own.
