### ISSUE TITLE
Renaming of folder set for "Import Preset bindings" breaks the next invocations of the same command.

### ISSUE THREAD

**Issue by vettukal** [haberdashPI/vscode-modal-keys#51]
How to reproduce the error:
1. Create a directory with name, `temp1`
2. Invoke `ModalKeys: Import Preset binding` and select `temp1` as the folder
3. Rename `temp1` to `temp2`
4. Invoke `ModalKeys: Import Preset binding` again and see the error.

**Comment by haberdashPI** [comment]
Ah, thank you. I will look into this....

**Comment by haberdashPI** [comment]
This should now be fixed on `main` and version 0.10.3 on the extension store.
